# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
  - jemoji
  - jekyll-paginate

# Site settings
title: "Stéphane Erbrech - Blog"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: stephane.erbrech@gmail.com
#blog logo
logo: "/blog/assets/images/logo.png"
# blog cover
cover: "/blog/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Stéphane Erbrech'
author: 'Stéphane Erbrech'
author_image: "/blog/assets/images/author.jpg"

paginate:	5

url: "http://serbrech.github.io/blog" # the base hostname & protocol for your site
baseurl: "/blog"
#used to display twitter cards
twitter_handle: '@serbrech'

#fill in disqus shortname to use disqus
disqus: serbrech

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/serbrech
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/serbrech
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
